config/routes.rb
MathpackClient::Application.routes.draw do
  root 'home#index'

  get 'home/index'
  post 'integration/solve'
  get 'plot/new'
  post 'plot/draw'
  get 'integration/new'
  get 'sle/new'
  post 'sle/change_dimension'
  post 'sle/solve'
  post 'home/csv'
  post 'plot/csv'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  around_filter :set_locale

  private

  def set_locale
    original_locale = I18n.locale
    available = %w(ru en)

    I18n.locale = if available.include?(locale = params[:locale].to_s.downcase)
                    locale
                  else
                    I18n.default_locale
                  end

    yield
  ensure
    I18n.locale = original_locale
  end
end

app/controllers/home_controller.rb
require 'graph'

class HomeController < ApplicationController
  #before_action :clear_token

  def index
    session[:state] ||= Digest::MD5.hexdigest(rand.to_s)
  end

  def get_graph
  	@graph = Graph.new([[0, 1, 1, 0, 0, 0, 0, 0],
												[1, 0, 1, 0, 0, 0, 0, 0],
												[1, 1, 0, 1, 0, 0, 0, 0],
												[0, 0, 1, 0, 1, 1, 0, 0],
												[0, 0, 0, 1, 0, 1, 1, 0],
												[0, 0, 0, 1, 1, 0, 1, 1],
												[0, 0, 0, 0, 1, 1, 0, 1],
												[0, 0, 0, 0, 0, 1, 1, 0]], ['distance', 'visited', 'predessor'], ['rank'])

  	render json: { nodes: @graph.vertexes.map(&:to_h), edges: @graph.edges.map(&:to_h)}.to_json
  end

  private

  def clear_token
    session[:token] = nil
    session[:vk_id] = nil
  end
end

app/controllers/integration_controller.rb
class IntegrationController < ApplicationController
  respond_to :js, only: :solve

  def new
    @integration_form = IntegrationForm.new
  end

  def solve
    @integration_form = IntegrationForm.new(integrate_params)
    @integration_form.process
  end

  private

  def integrate_params
    params.require(:integration_form).permit(:function, :from, :to)
  end
end

app/controllers/plot_controller.rb
class PlotController < ApplicationController
  # respond_to :js, only: :draw

  def new
    @plot_form = PlotForm.new
  end

  def draw
    @plot_form = PlotForm.new(plot_params)
    @plot_form.draw
  end

  def csv
    @plot_form = PlotForm.new
    @plot_form.from_csv_content(File.read(params[:file].path))
    @plot_form.draw

    render 'draw'
  end

  private

  def plot_params
    params.require(:plot_form).permit(:function, :from, :to)
  end
end

app/controllers/sle_controller.rb
class SleController < ApplicationController
  def new
    @sle_form = SleForm.new
  end

  def change_dimension
    @sle_form = SleForm.new(params[:sle_form][:sle_form].merge({dimension: params[:dimension]}))
  end

  def solve
    @sle_form = SleForm.new(params[:sle_form])
    @sle_form.solve
    render 'new'
  end
end

app/controllers/vkontakte_controller.rb
require 'graph'

class VkontakteController < ApplicationController
  before_action :set_friends, only: :build_graph
  before_action :set_client_and_user, only: :friends

  def login
    if session[:state] == params[:state]
      @vk = VkontakteApi.authorize(code: params[:code])

      session[:user_id] = @vk.user_id
      session[:token] = @vk.token
    end

    redirect_to vkontakte_friends_path
  end

  def friends
  end

  def build_graph
    @graph = Graph.new(@matrix, ['distance', 'visited', 'predessor'], ['rank'])

    render 'build_graph', locals: { nodes: @graph.vertexes.map(&:to_h).to_json, edges: @graph.edges.map(&:to_h).to_json }
  end

  private

  def set_client_and_user
    @client = VkontakteApi::Client.new(session[:token])
    @user = @client.users.get(uid: session[:user_id], fields: [:screen_name, :photo]).first
  end

  def set_friends
    set_client_and_user
    my_id = @user.uid

    my_friends = @client.friends.get

    friends = {}

    my_friends.each do |my_friend|
      begin
        friends[my_friend] = @client.friends.get(uid: my_friend)
      rescue Exception 
      end
    end

    friends[my_id] = my_friends
    my_friends << my_id

    person_index = {}

    my_friends.each_with_index do |person, index|
      person_index[person] = index
    end

    @matrix = Array.new(my_friends.length) { Array.new(my_friends.length, 0) }

    friends.each do |friend, his_friends|
      his_friends.each do |person|
        @matrix[person_index[friend]][person_index[person]] = 1 if my_friends.include?(person)
      end
    end

    @matrix[@matrix.length - 1][@matrix.length - 1] = 0
    @matrix
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/draw.js.erb
$(function () {
  new Highcharts.Chart({
    chart: { renderTo: 'orders_chart' },
    title: { text: 'Orders by Day' },
    xAxis: { tickInterval: 0.5 },
    yAxis: {
      title: { text: 'Dollars'}
    },
    series: [{
      data: <%= data %>,
      pointStart: 0
    }]
  });
});

app/views/home/index.html.slim
= link_to 'Enter vk', VkontakteApi.authorization_url(scope: [:friends, :groups, :offline, :notify], state: session[:state]), class: 'btn btn-default'

app/views/integration/_integration_fields.html.slim
= simple_form_for integration_form, remote: true, url: { action: :solve }, html: { class: 'form-inline', id: 'integral-form' } do |f|
  = f.input :function, required: false
  = f.input :from, required: false
  = f.input :to, required: false
  = f.button :submit, class: 'btn btn-primary'

#integral-answer.input-group
  input type="text" class="form-control" id="integration-result" placeholder="#{t('result')}" value="#{integration_form.result}"
  span.input-group-btn
  button class="my_clip_button" data-clipboard-target="integration-result" id="d_clip_button" class="btn btn-success"
    span.octicon.octicon-clippy

app/views/integration/integrate.html.slim
#integration_fields
  = render 'integration_fields', integration_form: @integration_form

app/views/integration/new.slim
#integration_fields
  = render 'integration_fields', integration_form: @integration_form

app/views/integration/solve.js.erb
$('#integration_fields').html('<%= j render('integration_fields', integration_form: @integration_form) %>');
var clip = new ZeroClipboard($("#d_clip_button"));

app/views/layouts/_messages.html.slim
- # Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    |  <div class="alert alert-
    = name.to_s == 'notice' ? 'success' : 'danger'
    | "> 
    button.close[type="button" data-dismiss="alert" aria-hidden="true"]
      | ×
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
- # navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Mathpack', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li = link_to t('navigation.integration'), integration_new_path
li = link_to t('navigation.plot'), plot_new_path
li = link_to t('navigation.sle'), sle_new_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : "Mathpack"
    |  <meta name="description" content="
    = content_for?(:description) ? yield(:description) : "Mathpack"
    | "> 
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'highcharts'
    script src="http://js.pusher.com/2.0/pusher.min.js"
    = favicon_link_tag 'calculator.png'
    = csrf_meta_tags
  body
    header
      = render 'layouts/navigation'
    main[role="main"]
      = render 'layouts/messages'
      = yield
    footer
      = render 'shared/about_me'

app/views/plot/_plot_fields.slim
= simple_form_for plot_form, remote: true, url: { action: :draw }, html: { class: 'form-inline', id: 'plot-form' } do |f|
  = f.input :function, required: false
  = f.input :from, required: false
  = f.input :to, required: false
  = f.button :submit, class: 'btn btn-primary'

app/views/plot/draw.js.erb
$(function () {
  $('#plot_fields').html('<%= j render('plot_fields', plot_form: @plot_form) %>');

  <%- if @plot_form.valid? %>
    new Highcharts.Chart({
      chart: { renderTo: 'function_plot' },
      title: { text: '<%= @plot_form.function %>' },
      xAxis: { tickInterval: <%= @plot_form.tick %> },
      yAxis: {
        title: { text: 'y'}
      },
      series: [{
        data: <%= @plot_form.data.to_json %>,
        pointStart: 0,
        name: '<%= @plot_form.function %>'
      }]
    });
  $('#function_plot').show();
  <%- else %>
    $('#function_plot').hide();
  <%- end %>
});

app/views/plot/new.slim
#plot_fields
  = render 'plot_fields', plot_form: @plot_form

b = t('other.download_from_csv')
= form_tag plot_csv_path, id: 'table-function-download', multipart: true, remote: true do
  = file_field_tag :file, class: 'file'
  = submit_tag t('other.download'), class: 'btn btn-primary'

#function_plot

app/views/plot/plot.slim
#plot_fields
  = render 'plot_fields', plot_form: @plot_form

b = t('other.download_from_csv')
= form_tag plot_csv_path, id: 'table-function-download', multipart: true, remote: true do
  = file_field_tag :file, class: 'file'
  = submit_tag t('other.download'), class: 'btn btn-primary'

#function_plot

app/views/sle/_sle_fields.slim
= simple_form_for sle_form, url: sle_solve_url do |f|
  = f.input :dimension, collection: (2..SleForm::MAX_DIMENSION).to_a, required: false, input_html: { data: { change_dim_url: sle_change_dimension_url }, id: 'matrix_dimension' }
  table#matrix-table
    - for i in 0...f.object.dimension do
      tr
        - for j in 0...f.object.dimension do
          td
            = f.input "matrix_#{i}_#{j}".to_sym, input_html: { class: 'matrix-cell' }, label: false, as: :decimal

  table
    - for i in 0...f.object.dimension do
      tr
        = f.input "f_#{i}".to_sym, input_html: { class: 'matrix-cell' }, label: false, as: :decimal

  = f.button :submit, class: 'btn btn-primary', id: 'solve-sle-button'

- if sle_form.result
  #sle_solution
    = "(#{sle_form.result.join('; ')})"

app/views/sle/change_dimension.js.erb
$(function () {
  $('#sle_fields').html('<%= j render('sle_fields', sle_form: @sle_form) %>');
});

app/views/sle/index.html.slim
= simple_form_for :matrix, url: sle_solve_url, remote: true do |f|
  = f.input :number, collection: (2..10).to_a, required: false, selected: 2, input_html: { data: { change_dim_url: sle_change_dimension_url } }, label: t('.number')
  .wrapper = render 'matrix', number: 2

#sle-solution

app/views/sle/new.slim
#sle_fields
  = render 'sle_fields', sle_form: @sle_form

app/views/vkontakte/build_graph.js.erb
$(function(){
  var nodes = new vis.DataSet(<%= nodes.html_safe %>);
  var edges = new vis.DataSet(<%= edges.html_safe %>);
	var container = $('#friends-graph')[0];
  var network = new vis.Network(container, {nodes: nodes, edges: edges}, {}); 
});

app/views/vkontakte/friends.html.slim
- if @user
	= link_to 'Show graph', vkontakte_build_graph_path, class: 'btn btn-default', remote: true

#friends-graph